import { getDb } from "../api/queries/connection";
import { categories, products } from "./schema";

async function seed() {
  const db = getDb();

  // Seed categories
  const cats = await db.insert(categories).values([
    { name: "Islamic Books", slug: "islamic-books", description: "Authentic Islamic literature for all ages and levels of knowledge.", image: "/cat-books.jpg", sortOrder: 1 },
    { name: "Islamic Electronics", slug: "islamic-electronics", description: "Technology to support your worship and learning.", image: "/cat-electronics.jpg", sortOrder: 2 },
    { name: "Children's Learning", slug: "childrens-learning", description: "Fun and educational Islamic products for children.", image: "/cat-children.jpg", sortOrder: 3 },
    { name: "Islamic Home Decor", slug: "islamic-home-decor", description: "Bring beauty and inspiration into your home.", image: "/cat-decor.jpg", sortOrder: 4 },
    { name: "Gifts & Accessories", slug: "gifts-accessories", description: "Thoughtful gifts for every occasion.", image: "/cat-gifts.jpg", sortOrder: 5 },
    { name: "Services", slug: "services", description: "Professional printing, design, and educational services.", image: "/cat-services.jpg", sortOrder: 6 },
  ]);

  console.log("Categories seeded:", cats);

  // Seed products
  const prods = await db.insert(products).values([
    {
      name: "The Noble Quran with English Translation",
      slug: "noble-quran-english",
      description: "A beautifully bound Quran with clear English translation, perfect for daily reading and study. Features easy-to-read Arabic script alongside accurate English translation.",
      shortDescription: "Beautifully bound Quran with clear English translation",
      price: "45.00",
      compareAtPrice: "55.00",
      categoryId: 1,
      image: "/product-quran-1.jpg",
      sku: "QUR-001",
      stockQuantity: 50,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      rating: "4.9",
      reviewCount: 128,
      tags: "quran,translation,islamic books,bestseller",
    },
    {
      name: "Digital Azan Clock with Prayer Times",
      slug: "digital-azan-clock",
      description: "Automatic azan clock with accurate prayer times for all cities worldwide. Features LED display, temperature, and date. Perfect for home or mosque use.",
      shortDescription: "Automatic prayer time clock with LED display",
      price: "89.99",
      compareAtPrice: "120.00",
      categoryId: 2,
      image: "/product-azan-clock.jpg",
      sku: "ELEC-001",
      stockQuantity: 30,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      rating: "4.7",
      reviewCount: 86,
      tags: "azan clock,prayer times,electronics,bestseller",
    },
    {
      name: "Al-Qalam Digital Quran Pen Reader",
      slug: "digital-quran-pen",
      description: "Advanced digital Quran pen that reads any verse you point to. Includes multiple reciter voices, translations in 20+ languages, and tafsir. Perfect for learning Quran.",
      shortDescription: "Point-and-read Quran pen with multiple reciters",
      price: "120.00",
      compareAtPrice: "150.00",
      categoryId: 2,
      image: "/product-quran-pen.jpg",
      sku: "ELEC-002",
      stockQuantity: 25,
      isActive: true,
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.8",
      reviewCount: 64,
      tags: "quran pen,digital,electronics,new arrival",
    },
    {
      name: "Premium Turkish Prayer Mat",
      slug: "premium-prayer-mat",
      description: "Luxurious prayer mat with intricate geometric patterns inspired by Islamic art. Soft, durable, and comfortable for daily prayers. Easy to fold and carry.",
      shortDescription: "Luxurious prayer mat with geometric patterns",
      price: "35.00",
      compareAtPrice: "45.00",
      categoryId: 5,
      image: "/product-prayer-mat.jpg",
      sku: "GIFT-001",
      stockQuantity: 100,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      rating: "4.6",
      reviewCount: 203,
      tags: "prayer mat,gifts,accessories,bestseller",
    },
    {
      name: "Amber Tasbih Prayer Beads (99 beads)",
      slug: "amber-tasbih-beads",
      description: "Handcrafted 99-bead tasbih made from genuine amber with ornate gold-plated dividers and tassel. Beautiful to hold and use for dhikr.",
      shortDescription: "Genuine amber tasbih with gold-plated accents",
      price: "28.00",
      compareAtPrice: "35.00",
      categoryId: 5,
      image: "/product-tasbih.jpg",
      sku: "GIFT-002",
      stockQuantity: 75,
      isActive: true,
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      rating: "4.8",
      reviewCount: 156,
      tags: "tasbih,prayer beads,gifts,bestseller",
    },
    {
      name: "Stories of the Prophets - Children's Book",
      slug: "stories-prophets-children",
      description: "Beautifully illustrated children's book featuring stories of the prophets in an engaging, age-appropriate format. Hardcover with vibrant full-color illustrations.",
      shortDescription: "Illustrated stories of the prophets for children",
      price: "18.00",
      compareAtPrice: "22.00",
      categoryId: 3,
      image: "/product-children-book.jpg",
      sku: "CHILD-001",
      stockQuantity: 60,
      isActive: true,
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.9",
      reviewCount: 92,
      tags: "children,books,islamic stories,new arrival",
    },
    {
      name: "Bismillah Islamic Calligraphy Wall Art",
      slug: "bismillah-wall-art",
      description: "Elegant framed Islamic calligraphy featuring Bismillah in stunning gold Thuluth script on black background. Modern gold frame, ready to hang. Perfect for any room.",
      shortDescription: "Gold Bismillah calligraphy in modern frame",
      price: "65.00",
      compareAtPrice: "80.00",
      categoryId: 4,
      image: "/product-wall-art.jpg",
      sku: "DECOR-001",
      stockQuantity: 40,
      isActive: true,
      isFeatured: true,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.7",
      reviewCount: 48,
      tags: "wall art,calligraphy,home decor,new arrival",
    },
    {
      name: "Oud Al-Ameer Premium Attar Perfume",
      slug: "oud-al-ameer-attar",
      description: "Luxurious concentrated perfume oil with rich oud, musk, and amber notes. Long-lasting fragrance in an ornate crystal bottle. Perfect for special occasions or daily use.",
      shortDescription: "Premium oud attar in ornate crystal bottle",
      price: "42.00",
      compareAtPrice: "55.00",
      categoryId: 5,
      image: "/product-attar.jpg",
      sku: "GIFT-003",
      stockQuantity: 45,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      rating: "4.8",
      reviewCount: 134,
      tags: "attar,perfume,gifts,bestseller",
    },
    {
      name: "Bluetooth Quran Speaker Cube",
      slug: "bluetooth-quran-speaker",
      description: "Compact Bluetooth speaker with full Quran recitation by multiple famous reciters. Also includes dua, adhan, and Islamic songs. Rechargeable battery, 8-hour playtime.",
      shortDescription: "Portable Quran speaker with Bluetooth",
      price: "55.00",
      compareAtPrice: "70.00",
      categoryId: 2,
      image: "/product-quran-speaker.jpg",
      sku: "ELEC-003",
      stockQuantity: 35,
      isActive: true,
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.5",
      reviewCount: 72,
      tags: "quran speaker,bluetooth,electronics,new arrival",
    },
    {
      name: "Islamic Learning Toys Set for Kids",
      slug: "islamic-learning-toys-set",
      description: "Complete set of Islamic educational toys including Arabic alphabet flashcards, talking prayer mat, Islamic world puzzle, and prayer rug. Makes learning fun and interactive.",
      shortDescription: "Complete Islamic learning set for children",
      price: "75.00",
      compareAtPrice: "95.00",
      categoryId: 3,
      image: "/product-learning-toys.jpg",
      sku: "CHILD-002",
      stockQuantity: 20,
      isActive: true,
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.6",
      reviewCount: 38,
      tags: "children,learning,toys,educational,new arrival",
    },
    {
      name: "Ruqyah Audio Device with Headphones",
      slug: "ruqyah-audio-device",
      description: "Portable Ruqyah audio player pre-loaded with authentic ruqyah recitations, healing surahs, and protective duas. Includes over-ear headphones for private listening.",
      shortDescription: "Portable Ruqyah player with healing recitations",
      price: "68.00",
      compareAtPrice: "85.00",
      categoryId: 2,
      image: "/product-ruqyah.jpg",
      sku: "ELEC-004",
      stockQuantity: 28,
      isActive: true,
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.7",
      reviewCount: 56,
      tags: "ruqyah,audio,electronics,healing,new arrival",
    },
    {
      name: "LED Crescent Moon & Star Wall Light",
      slug: "led-crescent-star-light",
      description: "Beautiful LED wall decoration featuring crescent moon and star design. Warm golden glow, perfect for Ramadan, Eid, or year-round Islamic home decor. USB powered.",
      shortDescription: "LED crescent moon wall light decoration",
      price: "32.00",
      compareAtPrice: "40.00",
      categoryId: 4,
      image: "/product-led-decor.jpg",
      sku: "DECOR-002",
      stockQuantity: 55,
      isActive: true,
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.4",
      reviewCount: 89,
      tags: "led,decor,ramadan,eid,home decor,new arrival",
    },
    {
      name: "Premium Islamic Gift Set",
      slug: "premium-islamic-gift-set",
      description: "Elegant gift box containing a velvet prayer mat, crystal tasbih beads, and a pocket-sized Quran. Beautifully packaged in a premium green and gold box with ribbon.",
      shortDescription: "Elegant gift set with prayer mat, tasbih, and Quran",
      price: "95.00",
      compareAtPrice: "120.00",
      categoryId: 5,
      image: "/product-gift-set.jpg",
      sku: "GIFT-004",
      stockQuantity: 30,
      isActive: true,
      isFeatured: true,
      isBestseller: true,
      isNewArrival: false,
      rating: "4.9",
      reviewCount: 167,
      tags: "gift set,prayer mat,tasbih,quran,bestseller",
    },
    {
      name: "Sahih Al-Bukhari - Complete Set (9 Volumes)",
      slug: "sahih-bukhari-complete",
      description: "The complete Sahih Al-Bukhari hadith collection in 9 volumes with English translation and commentary. Authenticated and published by Darussalam. Hardcover binding.",
      shortDescription: "Complete 9-volume Sahih Bukhari with translation",
      price: "150.00",
      compareAtPrice: "180.00",
      categoryId: 1,
      image: "/product-quran-1.jpg",
      sku: "BOOK-001",
      stockQuantity: 15,
      isActive: true,
      isFeatured: false,
      isBestseller: true,
      isNewArrival: false,
      rating: "4.9",
      reviewCount: 74,
      tags: "hadith,bukhari,islamic books,bestseller",
    },
    {
      name: "Tafsir Ibn Kathir - Abridged Version",
      slug: "tafsir-ibn-kathir",
      description: "The classic Tafsir Ibn Kathir in an accessible abridged format. Comprehensive commentary on the Quran with historical context and scholarly insights.",
      shortDescription: "Abridged Tafsir Ibn Kathir commentary",
      price: "55.00",
      compareAtPrice: "65.00",
      categoryId: 1,
      image: "/cat-books.jpg",
      sku: "BOOK-002",
      stockQuantity: 25,
      isActive: true,
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.8",
      reviewCount: 45,
      tags: "tafsir,ibn kathir,islamic books,quran study,new arrival",
    },
    {
      name: "Arabic Learning for Beginners",
      slug: "arabic-learning-beginners",
      description: "Comprehensive Arabic language learning book for beginners. Covers alphabet, basic grammar, vocabulary, and common phrases. Perfect for non-Arabic speakers wanting to understand Quran.",
      shortDescription: "Beginner's guide to learning Arabic",
      price: "25.00",
      compareAtPrice: "30.00",
      categoryId: 1,
      image: "/blog-books-review.jpg",
      sku: "BOOK-003",
      stockQuantity: 40,
      isActive: true,
      isFeatured: false,
      isBestseller: false,
      isNewArrival: true,
      rating: "4.5",
      reviewCount: 63,
      tags: "arabic,learning,language,islamic books,new arrival",
    },
  ]);

  console.log("Products seeded:", prods);
  console.log("Seed complete!");
}

seed().catch(console.error);
